version: "3.8"

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stackle_admin_app
    restart: unless-stopped
    networks:
      - caddy_gateway

networks:
  caddy_gateway:
    external: true
