version: '3.8'

services:
  frontend:
    build:
      context: .
    expose:
      - "8080"
    networks:
      - caddy_gateway
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/"]
      interval: 5s
      timeout: 3s
      retries: 3
    deploy:
      update_config:
        order: start-first
        failure_action: rollback

networks:
  caddy_gateway:
    external: true