version: '3.8'

services:
  frontend:
    image: ghcr.io/nived-manoj/stackle-web-admin:latest
    expose:
      - "8080"
    networks:
      - caddy_gateway
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
    deploy:
      update_config:
        order: start-first
        failure_action: rollback

networks:
  caddy_gateway:
    external: true